model_name: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
model_type: huggingface_models
base_model_name: deepseek-ai/DeepSeek-R1-Distill-Llama-8B

# Context length, should not handle longer contexts correctly
model_max_length: 8192

# only used for making savefile directory
model_name_summary: DeepSeek-R1-Distill-Llama-8B/DeepSeek-R1-Distill-Llama-8B

# tokenizer name, used for tokenizer_separator
tokenizer_name: deepseek-ai/DeepSeek-R1-Distill-Llama-8B

# used for saving files
save_file_name: DeepSeek-R1-Distill-Llama-8B

finetuned_tokenizer: False

# use flash attention, only false for gemma among the models we have
use_flash_attention: True