model_name: Magpie-Align/Llama-3-8B-WildChat
model_type: huggingface_models
base_model_name: Magpie-Align/Llama-3-8B-WildChat

# Context length, should not handle longer contexts correctly
model_max_length: 8192

# only used for making savefile directory
model_name_summary: LLama-3-8B-WildChat/LLama-3-8B-WildChat

# tokenizer name, used for tokenizer_separator
tokenizer_name: Magpie-Align/Llama-3-8B-WildChat

# used for saving files
save_file_name: LLama-3-8B-WildChat

finetuned_tokenizer: False

# use flash attention, only false for gemma among the models we have
use_flash_attention: True