model_name: /scratch/gpfs/zs7353/Llama-3.1-8B-Instruct
model_type: vllm_models
base_model_name: /scratch/gpfs/zs7353/Llama-3.1-8B-Instruct

# Context length, should not handle longer contexts correctly
model_max_length: 8192

# only used for making savefile directory
model_name_summary: Meta-Llama-3.1-8B-Instruct/Meta-Llama-3.1-8B-Instruct

# tokenizer name, used for tokenizer_separator
tokenizer_name: /scratch/gpfs/zs7353/Llama-3.1-8B-Instruct

# used for saving files
save_file_name: Meta-Llama-3.1-8B-Instruct

finetuned_tokenizer: False

# use flash attention, only false for gemma among the models we have
use_flash_attention: True