model_name: Qwen/Qwen2.5-7B-Instruct
model_type: huggingface_models
base_model_name: Qwen/Qwen2.5-7B-Instruct

# Context length, should not handle longer contexts correctly
model_max_length: 2048

# only used for making savefile directory
model_name_summary: Qwen2.5-7B-Instruct/Mistral-7B-Instruct-v0.3

# tokenizer name, used for tokenizer_separator
tokenizer_name: Qwen2.5-7B-Instruct/Qwen2.5-7B-Instruct

# used for saving files
save_file_name: Qwen2.5-7B-Instruct

finetuned_tokenizer: False

# use flash attention, only false for gemma among the models we have
use_flash_attention: True