model_name: mistralai/Mistral-7B-Instruct-v0.1
model_type: huggingface_models
base_model_name: mistralai/Mistral-7B-Instruct-v0.1

# Context length, should not handle longer contexts correctly
model_max_length: 8192

# only used for making savefile directory
model_name_summary: Mistral-7B-Instruct-v0.1/Mistral-7B-Instruct-v0.1

# tokenizer name, used for tokenizer_separator
tokenizer_name: mistralai/Mistral-7B-Instruct-v0.1